#!/bin/bash
DOMAINS_FILE="cache_domains.txt"
OUTPUT_FILE="unbound-lancache-overrides.conf"
TARGET_IP="172.16.172.10"

echo "# Autogenerated Unbound config for LanCache rewrites" > $OUTPUT_FILE

while read domain; do
    echo "local-zone: \"${domain}.\" redirect" >> $OUTPUT_FILE
    echo "local-data: \"${domain}. A ${TARGET_IP}\"" >> $OUTPUT_FILE
done < "$DOMAINS_FILE"

echo "✅ Config generated: $OUTPUT_FILE"
